version: '3.7'

services:
  
  web:
    image: mariort/php-nginx:3.0
    container_name: wordpress
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/www
    ports:
      - "8080:80"
    environment: 
      - XDEBUG_CONFIG
    networks:
      - default
    command: bash /www/docker/shell/webserver.sh

  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: wordpress-db
    volumes:
      - ./wordpress/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - default

networks:
  default:
    name: wordpress